apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      labels:
        app: factorio
    spec:
      containers:
        - name: factorio
          image: factoriotools/factorio:1.0
          imagePullPolicy: Always
          command: ["sh", "-c"]
          args:
            - |
              echo $MODLIST > /factorio/mods/mod-list.json
              echo $RCONPW > /factorio/config/rconpw
              echo $BANLIST > /factorio/config/server-banlist.json
              exec /docker-entrypoint.sh
          ports:
            - name: factorio
              containerPort: 34197
              protocol: UDP
            - name: rcon
              containerPort: 27015
              protocol: TCP
          resources:
            requests:
              cpu: "0.25"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: TZ
              value: Asia/Tokyo
            - name: UPDATE_MODS_ON_START
              value: "true"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: factorio-userinfo
                  key: FACTORIO_USERNAME
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: factorio-userinfo
                  key: FACTORIO_TOKEN
            - name: MODLIST
              valueFrom:
                configMapKeyRef:
                  name: facotiro-modlist
                  key: mod-list.json
            - name: BANLIST
              valueFrom:
                configMapKeyRef:
                  name: factorio-server-settings
                  key: server-banlist.json
            - name: RCONPW
              valueFrom:
                secretKeyRef:
                  name: factorio-rconpw
                  key: rconpw
          volumeMounts:
            - name: saves
              mountPath: /factorio/saves
            - name: mods
              mountPath: /factorio/mods
      volumes:
        - name: saves
          persistentVolumeClaim:
            claimName: factorio-pvc-saves
        - name: mods
          persistentVolumeClaim:
            claimName: factorio-pvc-mods
