apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: factorio-networkpolicy
spec:
  podSelector:
    matchLabels:
      app: factorio
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 34197
        - protocol: TCP
          port: 27015
  policyTypes:
    - Ingress
