apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-pvc-saves
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-pvc-mods
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
