kind: Service
apiVersion: v1
metadata:
  name: factorio
spec:
  type: NodePort
  selector:
    app: factorio
  ports:
    - name: factorio
      targetPort: factorio
      port: 34197
      protocol: UDP
    - name: rcon
      targetPort: rcon
      port: 27015
      protocol: TCP
status:
  loadBalancer: {}
